layout_spectrum: 0.3437160588800907
typography_spectrum: 0.17656763992272317
color:
  brandStrength: 0.46141424984671175
  lightness: 0.28028891794383526
  saturation: 0.7321344462689012
  rhythmicContrast: 0.416314210742712
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
github: true
author:
  name: Kirill
  email: ozeritski@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/08c6b83f-20a1-42c2-9f77-1ab59fd54624.png
name: lobusch-consulting.com
navigation:
  - name: Consulting
    id: daeacf41-ccc4-4eb2-9b5a-221f7382d589
    type: content
  - name: Kind human resources
    id: 4634e5e2-e5e1-4515-8316-777d7009c365
    type: content
  - name: Corporate resources
    id: 47d61d97-3eaa-43a3-b44c-1c3062558a33
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/abe06533-2e4a-4550-82b0-86963956dbc9.ico
title: Globusch party
description: >-
  A team of German and Ukrainian management consultants guiding in the Ukrainian
  business environment. Our team of partners consults in the areas of
  Management, Human Resources and Law.
purpose:
  - type: contact
    url: 'mailto:ozeritski@gmail.com'
    label: Contact me
  - type: external
    url: 'http://lobusch-consulting.com'
    label: Go to globusch origin
